### ISSUE TITLE
[Perlin] Параллелизм

### ISSUE THREAD

**Issue by pavel-b-novikov** [12202gavrilov/nsudotnet#1]
Распараллелите на Task-ах - индивидуально получите 9 баллов и 5 в зачетку.

**Comment by 12202gavrilov** [comment]
Хорошо, что есть на данный момент:
Распараллелено вычисление цветовых подсеток - ускорение ~ в 2.2-2.5 раза.
Добавлен параллелизм в вычислении сеток - ускорение незначительное ~ 1.2-1.5 раз.
Всего: Х2.5-2.7

Попытка использовать parallel for - схожие показатели ускорения при использовании отдельно, замедление при совместном с задачами (ожидаемо).
Попытка использовать unsafe-кодирование - ускорение незначительное.

Все-таки не совсем понятно, какую альтернативу методу WaitAll можно было бы использовать - в барьерной синхронизации особого смысла (при таком подходе) нет, как и в конструкции WhenAll.ContinueWith, так как сбор цветов - хех - без разницы как проделывать (синхронно, или нет). Разве что, еще можно попробовать параллельно собирать цвета, но ощутимого прироста скорости за счет наличия интерполяции на той же самой площади - особенно при большом количестве сеток - при текущем подходе,как мне кажется, не будет.

Скорее всего, я чего-то не понял, или не знаю чего-то такого про WaitAll или сам подход к распараллеливанию. Если это еще возможно, ожидаю комментариев по этому поводу.

P.S. Источник сведений по unsafe-работе с битмапами: http://habrahabr.ru/post/60085/
Насколько достижимы (в какой-либо мере) приложенные в конце результаты?

**Comment by pavel-b-novikov** [comment]
Принято.
